### ISSUE TITLE
Paru does not work on windows? 

### ISSUE THREAD

**Issue by htdebeer** [htdebeer/paru#30]
Related to [pandocomatic issue: trying out pandocomatic 0.2 first time user, unable to execute hello world example #43](https://github.com/htdebeer/pandocomatic/issues/43) by agusmba.

When I try to run

```{.ruby}
require 'paru/pandoc'

converter = Paru::Pandoc.new do
	from "markdown"
	to "html"
end

result = converter << "hello *world*"
```

on Windows, I get the message:

```
$ ruby test_paru.rb
pandoc: \
: openFile: invalid argument (Invalid argument)
C:/Ruby24/lib/ruby/gems/2.4.0/gems/paru-0.2.5.9/lib/paru/pandoc.rb:299:in `run_converter': error while running: (Paru::Error)

pandoc  --from=markdown \
        --to=html

Pandoc responded with:

pandoc: \
: openFile: invalid argument (Invalid argument)

        from C:/Ruby24/lib/ruby/gems/2.4.0/gems/paru-0.2.5.9/lib/paru/pandoc.rb:153:in `convert'
        from test_paru.rb:8:in `<main>'
```

**Comment by htdebeer** [comment]
Looking into this issue, using the string `" \\\n\t"` as a separator for command-line options seem to be the problem on Windows. Using a space instead seems to overcome this problem, but if I run the test set on Windows, it does complain about paths with escaped spaces in them.

**Comment by htdebeer** [comment]
Fixed the issue with the `\`; [creating separate issue for failing tests with spaces on windows](https://github.com/htdebeer/paru/issues/31)
