### ISSUE TITLE
Running the same paru filter in Windows fails compared to Linux/macOS

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#56]
Hi Huub, hope you've kept well over the last few challenging months!

I normally use macOS or Linux, but I was recently asked about using my pandocomatic workflow on Windows. I've been converting over my filters (making sure they have `.rb` suffix so Windows+Pandoc knows they are scripts). But I've hit a curious problem with pandocomatic. I have WSL (so I can run Linux under windows), and have installed Pandoc, Ruby 2.7.1 and pandocomatic/paru there. I have also installed Windows versions of Ruby 2.7.1 and Pandoc separately via a windows package manager scoop. Pandoc works directly in either environment, as does Ruby. My pandoc data directory is symlinked to the correct place for Windows ` C:\Users\cog\AppData\Roaming\pandoc` and Linux `/home/cog/.local/share/pandoc` -- thus the `pandocomatic.yaml` and filter files themselves are identical.

```markdown
---
title: Simple Test3
author: Joanna Doe
pandocomatic_:
  use-template: test2
  pandoc:
    verbose: true
---

# Title
Here is some text.
```

filters/noop.rb
```ruby
#!/usr/bin/env ruby

require 'paru/filter'

Paru::Filter.run do
  stop!
end
```

```yaml
  test2:
    pandoc:
      from: markdown
      to: html5
      standalone: true
      self-contained: true
      mathjax: true
      filter:
        - filters/noop.rb
    metadata:
      lang: 'EN-GB'
```

If I run a simple test.md file via WSL everything is fine:

```
PS C:\Users\cog> wsl pandocomatic ./test.md
[INFO] Running filter /home/cog/.local/share/pandoc/filters/noop.rb
[INFO] Completed filter /home/cog/.local/share/pandoc/filters/noop.rb in 3 ms
Pandocomatic needed 0.3 seconds to convert '/mnt/c/Users/cog/test.md' to 'test.html'.
```

BUT, if I use windows powershell on exactly the same file:
```
PS C:\Users\cog> pandocomatic.bat ./test.md
C:/Users/cog/scoop/apps/ruby/2.7.1-1/lib/ruby/2.7.0/psych.rb:456:in `parse': (<unknown>): did not find expected ',' or '}' while parsing a flow mapping at line 1 column 1 (Psych::SyntaxError)
        from C:/Users/cog/scoop/apps/ruby/2.7.1-1/lib/ruby/2.7.0/psych.rb:456:in `parse_stream'
        from C:/Users/cog/scoop/apps/ruby/2.7.1-1/lib/ruby/2.7.0/psych.rb:390:in `parse'
        from C:/Users/cog/scoop/apps/ruby/2.7.1-1/lib/ruby/2.7.0/psych.rb:277:in `load'
        from C:/Users/cog/scoop/persist/ruby/gems/gems/paru-0.4.0.2/lib/paru/filter/metadata.rb:52:in `initialize'
        from C:/Users/cog/scoop/persist/ruby/gems/gems/paru-0.4.0.2/lib/paru/filter.rb:272:in `new'
        from C:/Users/cog/scoop/persist/ruby/gems/gems/paru-0.4.0.2/lib/paru/filter.rb:272:in `filter'
        from C:/Users/cog/scoop/persist/ruby/gems/gems/paru-0.4.0.2/lib/paru/filter.rb:244:in `run'
        from C:/Users/cog/AppData/Roaming/pandoc/filters/noop.rb:5:in `<main>'
Error running filter C:/Users/cog/AppData/Roaming/pandoc/filters/noop.rb:
Filter returned error status 1
Error running pandoc => error while running:

"pandoc"        --verbose --from="markdown" --to="html5" --standalone --self-contained --mathjax --filter="C:/Users/cog/AppData/Roaming/pandoc/filters/noop.rb"

Pandoc responded with:

C:/Users/cog/scoop/apps/ruby/2.7.1-1/lib/ruby/2.7.0/psych.rb:456:in `parse': (<unknown>): did not find expected ',' or '}' while parsing a flow mapping at line 1 column 1 (Psych::SyntaxError)
        from C:/Users/cog/scoop/apps/ruby/2.7.1-1/lib/ruby/2.7.0/psych.rb:456:in `parse_stream'
        from C:/Users/cog/scoop/apps/ruby/2.7.1-1/lib/ruby/2.7.0/psych.rb:390:in `parse'
        from C:/Users/cog/scoop/apps/ruby/2.7.1-1/lib/ruby/2.7.0/psych.rb:277:in `load'
        from C:/Users/cog/scoop/persist/ruby/gems/gems/paru-0.4.0.2/lib/paru/filter/metadata.rb:52:in `initialize'
        from C:/Users/cog/scoop/persist/ruby/gems/gems/paru-0.4.0.2/lib/paru/filter.rb:272:in `new'
        from C:/Users/cog/scoop/persist/ruby/gems/gems/paru-0.4.0.2/lib/paru/filter.rb:272:in `filter'
        from C:/Users/cog/scoop/persist/ruby/gems/gems/paru-0.4.0.2/lib/paru/filter.rb:244:in `run'
        from C:/Users/cog/AppData/Roaming/pandoc/filters/noop.rb:5:in `<main>'
Error running filter C:/Users/cog/AppData/Roaming/pandoc/filters/noop.rb:
Filter returned error status 1
```

This error normally comes when the metadata is incorrect, but in this case it is read fine under linux. I've tried changing between LF and CRLF and that had no effect. 

Do you have any idea what could cause this error?

**Comment by htdebeer** [comment]
Yes. Apparently, [YAML does not allow TAB characters for indentation](https://yaml.org/faq.html). If you replace the TAB characters by two spaces in your test input file, the issue should be resolved. 

Note that this is a pandocomatic issue, not a paru issue.

**Comment by iandol** [comment]
Hi, I always try to ensure my YAML has spaces not tabs, and it does in this case (whitespace visualised in VS Code, copied from the post above, also this is the case for the original test.md file):

![Screenshot 2020-06-24 at 17 35 39](https://user-images.githubusercontent.com/153905/85531567-775e0000-b641-11ea-844e-4ccd416457a1.png)

Yes, sorry to file this in the wrong project, the stacktrace shows paru and I didn't focus on the call to metadata...

**Comment by htdebeer** [comment]
When I tried to reproduce your issue on MS Window, I used tabs and got the issue. Changing to spaces resolved that and I did not look any further. 

When I tried your actual example, I had to change the bottom `---` to `...` to get the YAML block recognized at all. That changed, I got the following error:

```
Pandoc responded with:

[INFO] Running filter C:/Users/.../noop.rb
Error running filter C:/Users/.../noop.rb
Could not find executable C:/Users/.../noop.rb
```

However, when I run the underlying pandoc command directly, thus not via pandocomatic, it finds and runs  "noop.rb" just fine. I tried to resolve this by changing to an absolute path, using backslashes as path separator, but to no avail. I tried in both the `cmd` and the `powershell`, to the same effect. I tried without a template and add the filter in the test input file, but no luck there either.

As I am not a Windows user, I am not sure how to proceed to get pandocomatic to run this filter on Windows to reproduce your issue.
