### ISSUE TITLE
undefined method `[]' for nil:NilClass (NoMethodError) while trying to parse pandoc --version

### ISSUE THREAD

**Issue by technicalpickles** [htdebeer/paru#61]
I'm getting an error with paru 0.4.2.1 and pandoc 2.10.1 with the identity filter example, ie:

```ruby
require "paru/filter"

Paru::Filter.run do 
  with "Span" do |span|
    binding.pry
    span
  end
end
```

```
Traceback (most recent call last):
        10: from ./sparse-markdown.rb:5:in `<main>'
         9: from ./sparse-markdown.rb:5:in `require'
         8: from /Users/technicalpickles/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/paru-0.4.2.1/lib/paru/filter.rb:20:in `<top (required)>'
         7: from /Users/technicalpickles/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/paru-0.4.2.1/lib/paru/filter.rb:20:in `require_relative'
         6: from /Users/technicalpickles/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/paru-0.4.2.1/lib/paru/filter/document.rb:21:in `<top (required)>'
         5: from /Users/technicalpickles/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/paru-0.4.2.1/lib/paru/filter/document.rb:21:in `require_relative'
         4: from /Users/technicalpickles/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/paru-0.4.2.1/lib/paru/filter/node.rb:19:in `<top (required)>'
         3: from /Users/technicalpickles/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/paru-0.4.2.1/lib/paru/filter/node.rb:19:in `require_relative'
         2: from /Users/technicalpickles/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/paru-0.4.2.1/lib/paru/pandoc.rb:25:in `<top (required)>'
         1: from /Users/technicalpickles/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/paru-0.4.2.1/lib/paru/pandoc.rb:81:in `<module:Paru>'
/Users/technicalpickles/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/paru-0.4.2.1/lib/paru/pandoc.rb:239:in `<class:Pandoc>': undefined method `[]' for nil:NilClass (NoMethodError)
```

It looks like it's looking for the string `User data directory` in `pandoc --version`:

```
pandoc 2.10.1
Compiled with pandoc-types 1.21, texmath 0.12.0.2, skylighting 0.8.5
Default user data directory: /Users/technicalpickles/.local/share/pandoc or /Users/technicalpickles/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

The difference is `Default user directory` vs `User directory`. A few ways to possibly fix:

- make the regex case insensitive
- check for both cases, `(?:Default user directory|User directory): `

**Comment by htdebeer** [comment]
Please upgrade pandoc to version >= 2.11. [Paru version >= 0.4.2](https://github.com/htdebeer/paru/releases/tag/0.4.2.1) supports only pandoc version >= 2.11 because of incompatible changes in pandoc.

**Comment by technicalpickles** [comment]
Thank you, confirmed that upgrading fixed it.

Would it be possible to check the version of pan doc, and fail with an error to upgrade?

**Comment by htdebeer** [comment]
:-)

Actually, the piece of code that broke was built for that purpose a couple of years ago! But yes, I need to make it more robust. I'll put it on the list for an possible next version of paru

**Comment by htdebeer** [comment]
Fix will be available in the next version of paru.
