### ISSUE TITLE
Error in psych called by paru

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#63]
Hi Huub, with the latest V2.16.1 Pandoc I have an error with my paru based filters; the error is in psych (unspecified class: Date) but this wasn't an issue last week, and the filter code is the same.

```
::: /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Date (Psych::DisallowedClass)
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/class_loader.rb:28:in `load'
::: 	from (eval):2:in `date'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/scalar_scanner.rb:59:in `tokenize'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:65:in `deserialize'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:128:in `visit_Psych_Nodes_Scalar'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:30:in `visit'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:35:in `accept'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `each'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:30:in `visit'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:35:in `accept'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:345:in `block in revive_hash'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `each'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `each_slice'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:343:in `revive_hash'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:167:in `visit_Psych_Nodes_Mapping'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:30:in `visit'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:35:in `accept'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:30:in `visit'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/visitor.rb:6:in `accept'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/visitors/to_ruby.rb:35:in `accept'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych.rb:335:in `safe_load'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych.rb:370:in `load'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/paru-0.4.2.3/lib/paru/filter/metadata.rb:52:in `initialize'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/paru-0.4.2.3/lib/paru/filter.rb:279:in `new'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/paru-0.4.2.3/lib/paru/filter.rb:279:in `filter'
::: 	from /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/paru-0.4.2.3/lib/paru/filter.rb:251:in `run'
::: 	from /Users/ian/.local/share/pandoc/filters/prependAll.rb:21:in `<main>'
::: Error running filter /Users/ian/.local/share/pandoc/filters/prependAll.rb:
::: Filter returned error status 1
```

```
❯ gem list | grep date
date (3.2.0, default: 3.1.0)
```

My environment:

---pandoc: /usr/local/bin/pandoc | V: 2.16.1
---pandocomatic: /Users/ian/.rbenv/shims/pandocomatic | V: 0.2.7.6
---ruby: /Users/ian/.rbenv/shims/ruby | V: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]
---rbenv versions:
  system
* 3.0.2 (set by RBENV_VERSION environment variable)
---rbenv: /usr/local/bin/rbenv
---gem: /Users/ian/.rbenv/shims/gem
---xelatex: /Library/TeX/texbin/xelatex
---latexmk: /Library/TeX/texbin/latexmk

**Comment by htdebeer** [comment]
Can you tell me how I can reproduce your scenario? Because my tests don't cover this issue at the moment, and I have no idea how to trigger the behavior that causes this issue.

**Comment by iandol** [comment]
The error is caused by an invalid date, can be reproduced in IRB using:

```ruby
❯ irb
irb(main):001:0> require "Psych"
=> true
irb(main):002:0> Psych.safe_load '2013-01-01'
/Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Date (Psych::DisallowedClass)
```

Why this is triggering now I don't know. Here is my minimal test case, note there is no date field anywhere in the YAML header:

```markdown
---
title: Test
author: Joanna Doe
pandocomatic_:
  use-template: test
---

# Test Doc 1

Some text is here.
```

`testyaml.yaml`

```yaml
settings:
  recursive: true
  follow-symlinks: false
  skip: ['.*', 'pandocomatic.yaml']
  match-files: 'first'
templates:
  test:
    pandoc:
      from: markdown
      to: html5
      standalone: true
      self-contained: true
      filter:
        - noop.rb
```

`noop.rb`

```ruby
#!/usr/bin/env ruby

require 'paru/filter'

Paru::Filter.run do
  stop!
end
```

RESULT:

```
❯ pandocomatic -b -c test.yaml testdate.md
pandoc	--from=markdown \
	--to=html5 \
	--standalone \
	--self-contained \
	--filter=noop.rb
/Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Date (Psych::DisallowedClass)
...
```

I did do a `gem update` recently. So either Pandoc is injecting a date now it wasn't before, or some change has been made to Psych or other Ruby library?

I will try to use a ruby debugger (byebug remote debugger) to inspect the metadata. I only know of byebug that allows remote debugging (i.e. I can break inside the paru filter execution called from Pandoc), do you know of any other ruby tools that can do this, I'd love to be able to do this inside an editor...

**Comment by iandol** [comment]
OK stepping through in the debugger, here is what gets received by paru:

```
[331, 340] in /Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/paru-0.4.2.3/lib/paru/filter.rb
   331:         # on STDIN that is being filtered
   332:         #
   333:         # @return [Document] create a new Document node from a pandoc AST from
   334:         #   JSON from STDIN
   335:         def read_document()
=> 336:             PandocFilter::Document.from_JSON @input.read
   337:         end
   338:
   339:         # Write the document being filtered to STDOUT
   340:         def write_document()
(byebug) @input.read
"{\"pandoc-api-version\":[1,22,1],\"meta\":{\"author\":{\"t\":\"MetaInlines\",\"c\":[{\"t\":\"Str\",\"c\":\"Joanna\"},{\"t\":\"Space\"},{\"t\":\"Str\",\"c\":\"Doe\"}]},\"pandocomatic-fileinfo\":{\"t\":\"MetaMap\",\"c\":{\"created\":{\"t\":\"MetaInlines\",\"c\":[{\"t\":\"Str\",\"c\":\"2021-11-04\"}]},\"from\":{\"t\":\"MetaInlines\",\"c\":[{\"t\":\"Str\",\"c\":\"markdown\"}]},\"modified\":{\"t\":\"MetaInlines\",\"c\":[{\"t\":\"Str\",\"c\":\"2021-11-04\"}]},\"path\":{\"t\":\"MetaInlines\",\"c\":[{\"t\":\"Str\",\"c\":\"/Users/ian/Desktop/Compile-mmd/testdate.md\"}]},\"src_path\":{\"t\":\"MetaInlines\",\"c\":[{\"t\":\"Str\",\"c\":\"/Users/ian/Desktop/Compile-mmd/testdate.md\"}]},\"to\":{\"t\":\"MetaInlines\",\"c\":[{\"t\":\"Str\",\"c\":\"html5\"}]}}},\"title\":{\"t\":\"MetaInlines\",\"c\":[{\"t\":\"Str\",\"c\":\"Test\"}]}},\"blocks\":[{\"t\":\"Header\",\"c\":[1,[\"test-doc-1\",[],[]],[{\"t\":\"Str\",\"c\":\"Test\"},{\"t\":\"Space\"},{\"t\":\"Str\",\"c\":\"Doc\"},{\"t\":\"Space\"},{\"t\":\"Str\",\"c\":\"1\"}]]},{\"t\":\"Para\",\"c\":[{\"t\":\"Str\",\"c\":\"Some\"},{\"t\":\"Space\"},{\"t\":\"Str\",\"c\":\"text\"},{\"t\":\"Space\"},{\"t\":\"Str\",\"c\":\"is\"},{\"t\":\"Space\"},{\"t\":\"Str\",\"c\":\"here.\"}]}]}"
```

The `yaml_string` variable:

```
(byebug) yaml_string
"---\nauthor: Joanna Doe\npandocomatic-fileinfo:\n  created: 2021-11-04\n  from: markdown\n  modified: 2021-11-04\n  path: /Users/ian/Desktop/Compile-mmd/testdate.md\n  src_path: /Users/ian/Desktop/Compile-mmd/testdate.md\n  to: html5\ntitle: Test\n---\n\n"
```

Which triggers the error on line 52 of metadata.rb:

```
   48:                     # Try to convert the YAML string to a Hash
   49:                     if yaml_string.empty?
   50:                         contents = {}
   51:                     else
=> 52:                         contents = YAML.load yaml_string
   53:                     end
```

The date in `pandocomatic-fileinfo` can cause that error:

```
irb(main):002:0> Psych.safe_load '2021-11-04'
/Users/ian/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/psych-4.0.2/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Date (Psych::DisallowedClass)
```

**Comment by iandol** [comment]
OK, if I revert Psych to 3.3.0 then the error doesn't trigger any more. I tried 4.0.0 and the error returns...

**Comment by iandol** [comment]
And yes, editing line 52 of metadata.rb to `contents = YAML.unsafe_load yaml_string` and the error goes away...

**Comment by iandol** [comment]
By the way, I just found that there is a relatively new "official" debug gem that fully supports remote debugging (even from VS Code or Chrome), this makes it really easy to breakpoint any ruby code run from Pandoc and inspect it in the terminal or GUI with all variables inspectable and a debug console available: https://github.com/ruby/debug

![Screenshot 2021-11-04 at 12 01 56_SMALL](https://user-images.githubusercontent.com/153905/140302892-0f9ff23e-9892-4074-b578-ea9bc71541d7.png)

**Comment by htdebeer** [comment]
Thanks for the debugging! And the tip!

I'll look into this tonight or somewhen later this week to see if using the "unsafe" method is a good idea, or if I can resolve the underlying issue why we need an unsafe call anyway.

**Comment by iandol** [comment]
👍🏼 -- here is some info I saw on my travels, it seems that `safe_load` (which now becomes `load` in V4+) only allows a limited set of inputs, and does not allow dates etc.:

https://makandracards.com/makandra/465149-ruby-the-yaml-safe_load-method-hides-some-pitfalls

It can be selectively added:

https://ruby-doc.org/stdlib-3.0.2/libdoc/psych/rdoc/Psych.html#method-c-safe_load 
```ruby
Psych.safe_load(yaml, permitted_classes: [Date])
```

**Comment by htdebeer** [comment]
Thanks for the solution! Worked like a charm. I've updated paru and pandocomatic.
