### ISSUE TITLE
0.2.4.7 error running hello world in Ruby V2.0

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#7]
If I try to run the "hello world" paru example with 0.2.4.7 (installed via gem) I get this error:

```
👉  test2
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter.rb:22:in `require_relative': /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter/document.rb:64: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '(' (SyntaxError)
Most likely cause: Paru expects a pandoc installation that has been
                               ^
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter/document.rb:66: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
check which pandoc-types have been compi...
           ^
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter/document.rb:66: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
check which pandoc-types have been compiled with your pand...
                             ^
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter/document.rb:76: syntax error, unexpected tCONSTANT, expecting keyword_do or '{' or '('
pandoc-types API version used in document (ve...
                ^
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter/document.rb:76: syntax error, unexpected keyword_in, expecting keyword_end
...andoc-types API version used in document (version = #{versio...
...                               ^
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter/document.rb:77: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
smaller than the version of pandoc-types used by paru
            ^
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter/document.rb:77: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
smaller than the version of pandoc-types used by paru
                                             ^
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter/document.rb:81: syntax error, unexpected keyword_end, expecting ')'
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter/document.rb:85: syntax error, unexpected keyword_end, expecting ')'
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter/document.rb:136: syntax error, unexpected keyword_end, expecting ')'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter.rb:22:in `<module:Paru>'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru/filter.rb:19:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru.rb:21:in `<module:Paru>'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.7/lib/paru.rb:19:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from ../test2:2:in `<main>'
```

What I think is happening is that you are using the indent-aware `<<~` for your HEREDOC errors (https://github.com/htdebeer/paru/blob/master/lib/paru/filter/document.rb#L61), which was only introduced in Ruby V2.3, and macOS uses V2.0 by default. I think it would be better to try to keep V2.0 compatibility, especially as you aren't really using the indentation feature of `<<~` anyway

**Comment by htdebeer** [comment]
True. I've applied your suggested fix in version 0.2.4.8.
