### ISSUE TITLE
Tests failing for raw_latex and example_blocks

### ISSUE THREAD

**Issue by UlyssesZh** [htdebeer/paru#86]
To reproduce, run `rake`.

```console
Started with run options --seed 30013

 FAIL MetadataFilterTest#test_raw_latex (4.40s)
        --- expected
        +++ actual
        @@ -2,9 +2,10 @@
         
         Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
         
        +```{=tex}
         \\begin{wrapfigure}{r}{0.3\\textwidth}
         \\centering
         \\includegraphics[width=0.25\\textwidth]{Cover Page.pdf}
         \\end{wrapfigure}
        -
        +```
         Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"
        /home/ulysses/projects/forks/paru/test/test_filter.rb:50:in `filter_file_and_equal_file'
        /home/ulysses/projects/forks/paru/test/test_filter.rb:297:in `test_raw_latex'

 FAIL MetadataFilterTest#test_example_blocks (4.88s)
        --- expected
        +++ actual
        @@ -7,7 +7,7 @@
         
         # Using the example block
         
        -:::: example
        +::: example
         ### Example 1: Adding your first example {#adding-your-first-example}
         
         Create an example block as follows: \\~\\~\\~{.markdown}
        @@ -19,7 +19,7 @@
         :::
         
         \\~\\~\\~
        -::::
        +:::
         
         ::: important
         Throughout the text, you can add example blocks like this. Furhtermore,
        /home/ulysses/projects/forks/paru/test/test_filter.rb:50:in `filter_file_and_equal_file'
        /home/ulysses/projects/forks/paru/test/test_filter.rb:223:in `test_example_blocks'

 FAIL FilterTest#test_example_blocks (15.24s)
        --- expected
        +++ actual
        @@ -7,7 +7,7 @@
         
         # Using the example block
         
        -:::: example
        +::: example
         ### Example 1: Adding your first example {#adding-your-first-example}
         
         Create an example block as follows: \\~\\~\\~{.markdown}
        @@ -19,7 +19,7 @@
         :::
         
         \\~\\~\\~
        -::::
        +:::
         
         ::: important
         Throughout the text, you can add example blocks like this. Furhtermore,
        /home/ulysses/projects/forks/paru/test/test_filter.rb:50:in `filter_file_and_equal_file'
        /home/ulysses/projects/forks/paru/test/test_filter.rb:223:in `test_example_blocks'

 FAIL FilterTest#test_raw_latex (20.24s)
        --- expected
        +++ actual
        @@ -2,9 +2,10 @@
         
         Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
         
        +```{=tex}
         \\begin{wrapfigure}{r}{0.3\\textwidth}
         \\centering
         \\includegraphics[width=0.25\\textwidth]{Cover Page.pdf}
         \\end{wrapfigure}
        -
        +```
         Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"
        /home/ulysses/projects/forks/paru/test/test_filter.rb:50:in `filter_file_and_equal_file'
        /home/ulysses/projects/forks/paru/test/test_filter.rb:297:in `test_raw_latex'

[WARNING] Deprecated: --self-contained. use --embed-resources --standalone=======================================================                     ] 85% Time: 00:00:20,  ETA: 00:00:04
File some_non_existing_file.bib not found in resource path===========================================================================                 ] 88% Time: 00:00:21,  ETA: 00:00:03
Error running filter ./test/filters/crashing_filter.rb:===================================================================================            ] 92% Time: 00:00:21,  ETA: 00:00:02
Error in $.blocks[0][4][1]: When parsing Text.Pandoc.Definition.Inline expected an Object with a tag field where the value is one of [Str, Emph, Underline, Strong, Strikeout, Superscript, Subscript, SmallCaps, Quoted, Cite, Code, Space, SoftBreak, LineBreak, Math, RawInline, Link, Image, Note, Span], but got Para.
  81/81: [===========================================================================================================================================] 100% Time: 00:00:21, Time: 00:00:21

Finished in 21.67842s
81 tests, 237 assertions, 4 failures, 0 errors, 0 skips
rake aborted!
Command failed with status (1)
/home/ulysses/.local/share/gem/ruby/3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

To make similar bugs easier to find in the future, consider using a GitHub Action to run tests automatically for you every time you push.

**Comment by htdebeer** [comment]
When I run `rake test TESTOPTS="--seed=30013"` on linux with pandoc 3.4 and ruby 3.3.5, all tests pass. Can you tell me which version of pandoc and ruby you used, and on what operating system? 

Looking at the test output failures you pasted, it looks like there's an extra newline added when running the filters in these failing tests.

Also, setting up GitHub actions might be a good idea. I'll look into this, but might take a while to setup because I've not used GitHub actions before.

**Comment by UlyssesZh** [comment]
Sorry, I should have included environment info. The Pandoc version is 3.1.11.1, and the Ruby version is 3.3.4. If this error is due to the old Pandoc version and you don't think that is a bug of paru, you may ignore my report of the test failing.

If you are not familiar with GitHub Actions, I may open a PR for that.

**Comment by htdebeer** [comment]
I think the failing errors might be due to the older pandoc version you're using. Some of paru's tests aren't pure unit tests because they depend on running an actual instance of pandoc. And pandoc's behavior does sometimes change from version to version.

Typically, I develop against the docker image defined in `Dockerfile`. I've started documenting that on [a separate page about paru development](documentation/development.md), but haven't gotten around finishing that page or adding it to the manual.

If you could raise a PR for the github actions, that'd be much appreciated!

**Comment by UlyssesZh** [comment]
Yes, it is the pandoc version that caused the problem. Installing the latest pandoc 3.4 fixes this.

The PR for gh action is opened at #88.
